import Head from "next/head";
import Navbar from "../components/Navbar";
import PizzaList from "../components/PizzaList";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pizza Restaurant in Brunei</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Slider />
      <PizzaList />
    </div>
  );
}
